### ISSUE TITLE
Cloudiness in generation

### ISSUE THREAD

**Issue by nighting0le01** [aimagelab/Alfie#2]
hi!! i see alot of cloudiness in my generations:
![image](https://github.com/user-attachments/assets/aa828305-a70c-4b11-8e31-b8be51f6e1c1)
![image](https://github.com/user-attachments/assets/315cc24f-a257-4356-aa12-f180401f18f2)
![image](https://github.com/user-attachments/assets/e53d6240-db68-4056-af6c-46db4d581e0e)

i used the settings: centering, do you have any recommendations on how can i reduce this cloudiness? will changing the base model to say Flux help???

**Comment by quattrinifabio** [comment]
Hi, can you specify the prompts and seed you are using? In general, there can be some cloudiness in the generation. To address this, you can tweak the prompt or generate using different seeds. 

We tried regenerating some of your images with the seed 2024 (the same used in the paper)
"An icon of a basketball"
![An icon of a basketball_centering_sz_512_seed_2024-rgba-alfie](https://github.com/user-attachments/assets/a7d1dae8-1b1c-426f-b192-4a8ed6f9f165)

"An illustration of a army helmet"
![An illustration of a army helmet_centering_sz_512_seed_2024-rgba-alfie](https://github.com/user-attachments/assets/d20fb9aa-2502-4a12-b48f-5ca634dc0763)


We are also planning to extend this code to work on different base models in the future.

**Comment by nighting0le01** [comment]
hi @quattrinifabio the basketball and the helmet you generated do have alot of cloudiness and white regions.

**Comment by quattrinifabio** [comment]
As we describe in the [paper](https://arxiv.org/pdf/2408.14826), we devise the parameter k to tune the intensity of the α channel, i.e. augmenting or reducing the opacity. This can also help with cloudiness.

We set this parameter k as 0.5 by [default](https://github.com/aimagelab/Alfie/blob/main/alfie/generate.py#L96), but it can be tuned during inference, e.g.
`python generate_prompt.py --setting centering-rgba-alfie --fg_prompt 'An icon of a basketball' --k 2`

This increases the opacity and results in the following image: 

![An icon of a basketball_centering_sz_512_seed_2024-rgba-alfieK_2](https://github.com/user-attachments/assets/8beb11d6-eba3-4217-a54f-c5aceb19b2dc)
